# Generated by Django 3.2.4 on 2021-06-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='permission',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='date',
            field=models.DateField(),
        ),
    ]
