# Generated by Django 3.2.4 on 2021-06-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210619_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
